-- VHDL module instantiation generated by SCUBA Diamond_2.2_Production (99)
-- Module  Version: 5.4
-- Thu Nov 28 23:23:44 2013

-- parameterized module component declaration
component pll_60MHz
    port (CLKI: in  std_logic; RST: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_60MHz
    port map (CLKI=>__, RST=>__, CLKOP=>__, LOCK=>__);
